from os import curdir
import sqlite3
from sqlite3.dbapi2 import Cursor, connect

# Usuários
def criar_tabela_usuario():
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    cursor.execute("CREATE TABLE IF NOT EXISTS usuarios(usuario TEXT, senha TEXT, adm BOOLEAN);")
    banco.commit()
    banco.close()

def inserir_usuario_por_modelo(usuario_banco):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_usuario()
    cursor.execute(f"INSERT INTO usuarios VALUES('{usuario_banco.usuario}', '{usuario_banco.senha}', {usuario_banco.adm == False});")
    banco.commit()
    banco.close()
    print(f"USUÁRIO INSERIDO")

def inserir_usuario_adm(usuario, senha, adm):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_usuario()
    cursor.execute(f"INSERT INTO usuarios VALUES('{usuario}', '{senha}', {adm});")
    banco.commit()
    banco.close()
    print(f"ADM INSERIDO")

def buscar_usuario_adm():
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_usuario()
    cursor.execute(f"SELECT * FROM usuarios WHERE usuario='rodrigo';")
    return cursor.fetchone()

def buscar_usuario(usuario):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_usuario()
    cursor.execute(f"SELECT rowid, * FROM usuarios WHERE usuario='{usuario}';")
    return cursor.fetchone()

def buscar_todos_os_usuarios():
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_usuario()
    cursor.execute(f"SELECT * FROM usuarios")
    return cursor.fetchall()

def alterar_login_senha(usuario_banco):
    banco = sqlite3.connect('banco.db')
    curso = banco.cursor()
    criar_tabela_usuario()
    curso.execute(f"UPDATE usuarios SET usuario='{usuario_banco.usuario}', senha='{usuario_banco.senha}' WHERE rowid='{usuario_banco.id}';")
    banco.commit()
    banco.close()
    print("LOGIN E SENHA ALTERADOS")

def alterar_dados_cleinte(cleinte_banco):
    banco = sqlite3.connect('banco.db')
    curso = banco.cursor()
    criar_tabela_cliente()
    curso.execute(f"UPDATE clientes SET nome='{cleinte_banco.nome}', cpf='{cleinte_banco.cpf}', email='{cleinte_banco.email}', telefone='{cleinte_banco.telefone}' WHERE cpf='{cleinte_banco.cpf}';")
    banco.commit()
    banco.close()
    print("DADOS ALTERADOS")

def remover_usuario_por_cliente_id(cliente_id):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_usuario()
    cursor.execute(f"DELETE FROM usuarios WHERE rowid='{cliente_id}'")
    banco.commit()
    banco.close()
    print(f"USUÁRIO DELETEADO")

def buscar_usuario_por_senha(senha):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_cliente()
    cursor.execute(f"SELECT * FROM usuarios WHERE senha='{senha}'")
    return cursor.fetchone()

# Clientes
def criar_tabela_cliente():
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    cursor.execute("CREATE TABLE IF NOT EXISTS clientes(nome TEXT, cpf TEXT, email TEXT, telefone TEXT, cliente_id INTERGER NOT NULL, FOREIGN KEY(cliente_id) REFERENCES usuarios(id));")
    banco.commit()
    banco.close()

def inserir_cliente_por_modelo(cleinte_banco):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_cliente()
    cursor.execute(f"INSERT INTO clientes VALUES('{cleinte_banco.nome}', '{cleinte_banco.cpf}', '{cleinte_banco.email}', '{cleinte_banco.telefone}', '{cleinte_banco.cliente_id}')")
    banco.commit()
    banco.close()
    print(f"CLIENTE INSERIDO")

def buscar_todos_os_clientes():
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_cliente()
    cursor.execute(f"SELECT * FROM clientes")
    return cursor.fetchall()

def buscar_cliente_por_nome(nome):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_cliente()
    cursor.execute(f"SELECT * FROM clientes WHERE nome LIKE '%{nome}%'")
    return cursor.fetchall()

def buscar_cliente_id(id):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_cliente()
    cursor.execute(f"SELECT * FROM clientes WHERE cliente_id={id}")
    return cursor.fetchone()

def buscar_cliente_por_nome_1(nome):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_cliente()
    cursor.execute(f"SELECT rowid, * FROM clientes WHERE nome='{nome}'")
    return cursor.fetchone()

def remover_cliente_por_nome(nome):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_cliente()
    cursor.execute(f"DELETE FROM clientes WHERE nome='{nome}'")
    banco.commit()
    banco.close()
    print(f"CLIENTE DELETEADO")

def buscar_cliente_por_cpf(cpf):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_cliente()
    cursor.execute(f"SELECT * FROM clientes WHERE cpf='{cpf}'")
    return cursor.fetchone()

# Macros
def criar_tabela_macros():
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    cursor.execute("CREATE TABLE IF NOT EXISTS macros(nome TEXT, proteina REAL, carboidratos REAL, gordura REAL, kcal INTERGER);")
    banco.commit()
    banco.close()

def inserir_macros_por_modelo(macro_banco):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_macros()
    cursor.execute(f"INSERT INTO macros VALUES('{macro_banco.nome}',{macro_banco.proteina},{macro_banco.carboidratos}, {macro_banco.gorduras}, {macro_banco.kcal})")
    banco.commit()
    banco.close()
    print(f"MACROS INSERIDOS")

def buscar_macro_banco_nome(macro_banco):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_macros()
    cursor.execute(f"SELECT * FROM macros WHERE nome='{macro_banco.nome}'")
    return cursor.fetchone()

# Dietas
def criar_tabela_dieta():
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    cursor.execute("CREATE TABLE IF NOT EXISTS dietas(proteina INTERGER,carboidratos INTERGER, gordura INTERGER, kcal INTERGER, dieta_id INTERGER NOT NULL, FOREIGN KEY(dieta_id) REFERENCES usuaros(id))")
    banco.commit()
    banco.close()

def inserir_dieta_usuario(proteina, carboidratos, gordura, kcal, dieta_id):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_dieta()
    cursor.execute(f"INSERT INTO dietas VALUES({proteina}, {carboidratos}, {gordura}, {kcal}, {dieta_id});")
    banco.commit()
    banco.close()
    print(f"DIETA INSERIDA")

def buscar_dieta(id):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_dieta()
    cursor.execute(f"SELECT * FROM dietas WHERE dieta_id='{id}'")
    return cursor.fetchone()

def alterar_dados_dieta(proteina,carboidratos,gordura,kcal,dieta_id):
    banco = sqlite3.connect('banco.db')
    curso = banco.cursor()
    criar_tabela_dieta()
    curso.execute(f"UPDATE dietas SET proteina={proteina}, carboidratos='{carboidratos}',gordura={gordura}, kcal={kcal},  dieta_id={dieta_id};")
    banco.commit()
    banco.close()
    print("DADOS DIETA ALTERADOS")

def remover_dieta_por_cliente_id(cliente_id):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_dieta()
    cursor.execute(f"DELETE FROM dietas WHERE rowid = {cliente_id}")
    banco.commit()
    banco.close()
    print(f"DIETA DELETADA")

# Calórico
def criar_tabela_calorico():
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    cursor.execute("CREATE TABLE IF NOT EXISTS calorias(proteina_kcal INTERGER, carboidratos_kcal INTERGER, gordura_kcal INTERGER, caloria_id INTERGER NOT NULL, FOREIGN KEY(caloria_id) REFERENCES usuaros(id));")
    banco.commit()
    banco.close()

def inserir_caloria_usuario(proteina_kcal, carboidratos_kcal, gordura_kcal, calorias_id):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_calorico()
    cursor.execute(f"INSERT INTO calorias VALUES({proteina_kcal}, {carboidratos_kcal}, {gordura_kcal}, {calorias_id})")
    banco.commit()
    banco.close()
    print(f"CALORIA INSERIDA")

def alterar_dados_calorico(proteina_kcal, carboidratos_kcal, gordura_kcal, caloria_id):
    banco = sqlite3.connect('banco.db')
    curso = banco.cursor()
    criar_tabela_calorico()
    curso.execute(f"UPDATE calorias SET proteina_kcal={proteina_kcal}, carboidratos_kcal={carboidratos_kcal}, gordura_kcal={gordura_kcal}, caloria_id={caloria_id}")
    banco.commit()
    banco.close()
    print("DADOS CALORICO ALTERADOS")

def remover_calorias_por_cliente_id(cliente_id):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_calorico()
    cursor.execute(f"DELETE FROM calorias WHERE rowid = {cliente_id}")
    banco.commit()
    banco.close()
    print(f"CALORICO DELETADA")

# TMB
def criar_tabela_tmb():
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    cursor.execute("CREATE TABLE IF NOT EXISTS tmb(kcal INTERGER, objetivo TEXT, peso INTERGER, altura INTERGER, idade INTERGER, genero TEXT, nivel_de_atividade TEXT, taxa_metabolica INTERGER, tmb_id INTERGER NOT NULL, FOREIGN KEY(tmb_id) REFERENCES usuaros(id))")
    banco.commit()
    banco.close()

def inserir_tmb_por_modelo(tmb_banco):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_tmb()
    cursor.execute(f"INSERT INTO tmb VALUES({tmb_banco.kcal}, '{tmb_banco.objetivo}', {tmb_banco.peso} {tmb_banco.altura}, {tmb_banco.idade}, '{tmb_banco.genero}',' {tmb_banco.nivel_de_atividade}', {tmb_banco.taxa_metabolica}, {tmb_banco.tmb_id})")
    banco.commit()
    banco.close()
    print(f"TMB INSERIDOS")

def inserir_tmb(kcal, objetivo, peso, altura, idade, genero, nivel_de_atividade, taxa_metabolica, tmb_id):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_tmb()
    cursor.execute(f"INSERT INTO tmb VALUES({kcal}, '{objetivo}', {peso}, {altura}, {idade}, '{genero}', '{nivel_de_atividade}', {taxa_metabolica}, {tmb_id})")
    banco.commit()
    banco.close()
    print(f"TMB INSERIDOS")

def buscar_tmb_por_id(id):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_tmb()
    cursor.execute(f"SELECT * FROM tmb WHERE tmb_id={id}")
    return cursor.fetchone()

def buscar_todos_tmb_por_id(id):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_tmb()
    cursor.execute(f"SELECT * FROM tmb WHERE tmb_id={id}")
    return cursor.fetchall()

def alterar_dados_tmb(kcal, objetivo, peso, altura, idade, genero, nivel_de_atividade, taxa_metabolica, tmb_id):
    banco = sqlite3.connect('banco.db')
    curso = banco.cursor()
    criar_tabela_tmb()
    curso.execute(f"UPDATE tmb SET kcal={kcal}, objetivo='{objetivo}', peso={peso}, altura={altura},  idade={idade}, genero='{genero}',nivel_de_atividade='{nivel_de_atividade}',taxa_metabolica={taxa_metabolica}, tmb_id={tmb_id};")
    banco.commit()
    banco.close()
    print("DADOS ALTERADOS")

def remover_tmb_por_id(id):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_tmb()
    cursor.execute(f"DELETE FROM tmb WHERE tmb_id={id}")
    banco.commit()
    banco.close()
    print(f"TMB DELETADA")

# Alimento
def criar_tabela_alimento():
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    cursor.execute("CREATE TABLE IF NOT EXISTS alimentos(refeicao TEXT, alimento TEXT, proteina INTERGER, carboidrato INTERGER, gordura INTERGER, quantidade INTERGER, alimentos_id INTERGER NOT NULL, FOREIGN KEY(alimentos_id) REFERENCES usuaros(id))")
    banco.commit()
    banco.close()

def inserir_alimentos(refeicao, alimento, proteina, carboidrato, gordura, quantidade, alimento_id):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_alimento()
    cursor.execute(f"INSERT INTO alimentos VALUES('{refeicao}', '{alimento}', {proteina}, {carboidrato}, {gordura}, {quantidade}, {alimento_id})")
    banco.commit()
    banco.close()
    print(f"ALIMENTO INSERIDO")

# Tabela Taco
def criar_tabela_taco():
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    cursor.execute("CREATE TABLE IF NOT EXISTS taco(alimento TEXT, kcal INTERGER, proteina INTERGER, gordura INTERGER, carboidrato INTERGER) ")
    banco.commit()
    banco.close()

def inserir_alimentos_taco(alimento, kcal, proteina, gordura, carboidrato):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_taco()
    cursor.execute(f"INSERT INTO taco VALUES('{alimento}', {kcal}, {proteina}, {gordura}, {carboidrato})")
    banco.commit()
    banco.close()
    
def buscar_aliemtos():
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_dieta()
    cursor.execute(f"SELECT * FROM taco")
    return cursor.fetchall()

def buscar_alimento_por_nome(nome):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_taco()
    cursor.execute(f"SELECT * FROM taco WHERE alimento LIKE '%{nome}%'")
    return cursor.fetchall()

def buscar_alimento_por_nome_1(nome):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_taco()
    cursor.execute(f"SELECT * FROM taco WHERE alimento='{nome}'")
    return cursor.fetchone()

# Tabela refeições 
def criar_tabela_refeicoes():
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    cursor.execute("CREATE TABLE IF NOT EXISTS refeicoes(numero_da_refeicao TEXT, quantidade INTERGER, alimento TEXT, calorias INTERGER, proteina INTERGER, gordura INTERGER, carboidrato INTERGER, refeicoes_id INTERGER NOT NULL, FOREIGN KEY(refeicoes_id) REFERENCES usuaros(id))")
    banco.commit()
    banco.close()

def inserir_refeicoes(numero_da_refeicao, quantidade, alimento, calorias, proteina, gordura, carboidrato, refeicoes_id):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_refeicoes()
    cursor.execute(f"INSERT INTO refeicoes VALUES('{numero_da_refeicao}', {quantidade}, '{alimento}', {calorias}, {proteina}, {gordura}, {carboidrato}, {refeicoes_id})")
    banco.commit()
    banco.close()

def buscar_refeicao_por_id(id):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_refeicoes()
    cursor.execute(f"SELECT * FROM refeicoes WHERE refeicoes_id={id}")
    return cursor.fetchall()

def buscar_refeicao_por_id_1(id):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_refeicoes()
    cursor.execute(f"SELECT numero_da_refeicao, alimento, quantidade FROM refeicoes WHERE refeicoes_id={id}")
    return cursor.fetchall()

def buscar_refeicao_por_id_2(id,numero_da_refeicao):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_refeicoes()
    cursor.execute(f"SELECT alimento, quantidade FROM refeicoes WHERE refeicoes_id={id} AND numero_da_refeicao='{numero_da_refeicao}'")
    return cursor.fetchall()

def remover_refeicao_po_usuario(id):
    banco = sqlite3.connect('banco.db')
    cursor = banco.cursor()
    criar_tabela_refeicoes()
    cursor.execute(f"DELETE FROM refeicoes WHERE refeicoes_id={id}")
    banco.commit()
    banco.close()
    print(f"REFEIÇÃO DELETADA")

# ADM
if __name__ == "__main__":
    usuario = buscar_usuario_adm()
    if usuario is None:
        inserir_usuario_adm("rodrigo", "123", True)
        inserir_alimentos_taco('Arroz integral cozido', 124, 3, 1, 26,)
        inserir_alimentos_taco('Arroz integral cru', 360, 7, 2, 77)
        inserir_alimentos_taco('Arroz Parbolizado cozido', 128, 3, 0, 28)
        inserir_alimentos_taco('Arroz Parbolizado cru', 358, 7, 0, 79)
        inserir_alimentos_taco('Arroz Branco cozido', 130, 3, 0, 28)
        inserir_alimentos_taco('Arroz Branco cru', 358, 7, 0, 79)
        inserir_alimentos_taco('Aveia flocos crua', 394, 14, 8, 67)
        inserir_alimentos_taco('Biscoito doce maisena', 443, 8, 12, 75)
        inserir_alimentos_taco('Biscoito doce recheado com chocolate', 472, 6, 20, 71)
        inserir_alimentos_taco('Biscoito doce recheado com morango', 471, 6, 20, 71)
        inserir_alimentos_taco('Biscoito doce wafer recheado de chocolate', 502, 6, 25, 68)
        inserir_alimentos_taco('Biscoito doce wafer recheado de morango', 513, 5, 26, 67)
        inserir_alimentos_taco('Biscoito salgado cream cracker', 432, 10, 14, 69)
        inserir_alimentos_taco('Bolo mistura', 419,6, 6, 85)
        inserir_alimentos_taco('Bolo pronto aipim', 324, 4, 13, 48)
        inserir_alimentos_taco('Bolo pronto chocolate', 410, 6, 18, 55)
        inserir_alimentos_taco('Bolo pronto coco', 333, 6, 11, 52)
        inserir_alimentos_taco('Bolo pronto milho', 311, 5, 12, 45)
        inserir_alimentos_taco('Canjica branca crua', 358, 7, 1, 78)
        inserir_alimentos_taco('Canjica com leite integral', 112, 2, 1, 24)
        inserir_alimentos_taco('Cereais milho flocos com sal', 370, 7, 2, 81)
        inserir_alimentos_taco('Cereais milho flocos sem sal', 363, 7, 1, 80)
        inserir_alimentos_taco('Cereais mingau milho infantil', 394, 6, 1, 87)
        inserir_alimentos_taco('Cereais mistura para vitamina trigo cevada e aveia', 381, 9, 2, 82)
        inserir_alimentos_taco('Cereal matinal milho', 365, 7, 1, 84)
        inserir_alimentos_taco('Cereal matinal milho com açúcar', 377, 5, 1, 89)
        inserir_alimentos_taco('Creme de arroz em pó', 386, 7, 1, 84)
        inserir_alimentos_taco('Creme de milho em pó', 333, 5, 2, 86)
        inserir_alimentos_taco('Curau milho verde', 78, 2, 2, 14)
        inserir_alimentos_taco('Curau milho verde mistura ', 402, 2, 13, 80)
        inserir_alimentos_taco('Farinha de arroz enriquecida', 363, 1, 0, 86)
        inserir_alimentos_taco('Farinha de centeio integral', 336, 13, 2, 73)
        inserir_alimentos_taco('Farinha de milho amarela', 351, 7, 1, 79)
        inserir_alimentos_taco('Farinha de rosca', 371, 11, 1, 76)
        inserir_alimentos_taco('Farinha de trigo', 360, 10, 1, 75)
        inserir_alimentos_taco('Farinha láctea, de cereais', 415, 12, 6, 78)
        inserir_alimentos_taco('Lasanha massa fresca cozida', 164, 6, 1, 33)
        inserir_alimentos_taco('Lasanha massa fresca crua', 220, 7, 1, 45)
        inserir_alimentos_taco('Macarrão instantâneo', 436, 9, 17, 62)
        inserir_alimentos_taco('Macarrão trigo cru', 371, 10, 1, 78)
        inserir_alimentos_taco('Macarrão trigo cru com ovos', 371, 10, 2, 77)
        inserir_alimentos_taco('Milho amido cru', 361, 1, 0, 87)
        inserir_alimentos_taco('Milho fubá cru', 353, 7, 2, 79)
        inserir_alimentos_taco('Milho verde cru', 138, 7, 1, 29)
        inserir_alimentos_taco('Milho verde enlatado drenado', 98, 3, 2, 17)
        inserir_alimentos_taco('Mingau tradicional em pó', 373, 1, 0, 89)
        inserir_alimentos_taco('Pamonha barra para cozimento pré-cozida', 171, 3, 5, 31)
        inserir_alimentos_taco('Pão aveia forma', 343, 12, 6, 60)
        inserir_alimentos_taco('Pão de soja', 309, 11, 4, 57)
        inserir_alimentos_taco('Pão glúten de forma', 253, 12, 3, 44)
        inserir_alimentos_taco('Pão milho de forma', 292, 8, 3, 56)
        inserir_alimentos_taco('Pão trigo forma integral', 253, 9, 4, 50)
        inserir_alimentos_taco('Pão trigo francês', 300, 8, 3, 59)
        inserir_alimentos_taco('Pão trigo sovado', 311, 8, 3, 61)
        inserir_alimentos_taco('Pastel de carne cru', 289, 11, 9, 42)
        inserir_alimentos_taco('Pastel de carne frito', 388, 10, 20, 44)
        inserir_alimentos_taco('Pastel de queijo cru', 308, 10, 10, 46)
        inserir_alimentos_taco('Pastel de queijo frito', 422, 9, 23, 48)
        inserir_alimentos_taco('Pastel massa crua',	310,	7,	5,	57)
        inserir_alimentos_taco('Pastel massa frita',	570,	6,	41,	49)
        inserir_alimentos_taco('Pipoca com óleo de soja sem sal',	448,	10,	16,	70)
        inserir_alimentos_taco('Polenta pré-cozida',	103,	2,	0,	23)
        inserir_alimentos_taco('Torrada de pão francês',	377,	11,	3,	75)					
        inserir_alimentos_taco('Abóbora cabotian cozida',	48,	1,	1,	11)
        inserir_alimentos_taco('Abóbora cabotian crua',	39, 2,	1,	8)
        inserir_alimentos_taco('Abóbora menina brasileira crua',	14,	1,	0,	3)
        inserir_alimentos_taco('Abóbora moranga crua',	12,	1,	0,	3)
        inserir_alimentos_taco('Abóbora moranga refogada',	29,	0,	1,	6)
        inserir_alimentos_taco('Abóbora pescoço crua',	24,	1,	0,	6)
        inserir_alimentos_taco('Abobrinha italiana cozida',	15,	1,	0,	3)
        inserir_alimentos_taco('Abobrinha italiana crua',	19,	1,	0,	4)
        inserir_alimentos_taco('Abobrinha italiana refogada',	24,	1,	1,	4)
        inserir_alimentos_taco('Abobrinha paulista crua',	31,	1,	0,	8)
        inserir_alimentos_taco('Acelga crua',	21,	1,	0,	5)
        inserir_alimentos_taco('Agrião cru',	17,	3,	0,	2)
        inserir_alimentos_taco('Aipo cru',	19,	1,	0,	4)
        inserir_alimentos_taco('Alface americana crua',	9,	1,	0,	2)
        inserir_alimentos_taco('Alface crespa crua',	11,	1,	0,	2)
        inserir_alimentos_taco('Alface lisa crua',	14,	2,	0,	2)
        inserir_alimentos_taco('Alface roxa crua',	13,	1,	0,	2)
        inserir_alimentos_taco('Alfavaca crua',	29,	3,	0,	5)
        inserir_alimentos_taco('Alho cru', 113,	7,	0,	24)
        inserir_alimentos_taco('Alho-poró cru',	32,	1,	0,	7)
        inserir_alimentos_taco('Almeirão cru',	18,	2,	0,	3)
        inserir_alimentos_taco('Almeirão refogado',	65,	2,	5,	6)
        inserir_alimentos_taco('Batata baroa cozida',	80,	1,	0,	19)
        inserir_alimentos_taco('Batata baroa crua',	101,	1,	0,	24)
        inserir_alimentos_taco('Batata doce cozida',	77,	1,	0,	18)
        inserir_alimentos_taco('Batata doce crua',	118,	1,	0,	28)
        inserir_alimentos_taco('Batata frita tipo chips industrializada',	543,	6,	37,	51)
        inserir_alimentos_taco('Batata inglesa cozida',	52,	1,	0,	12)
        inserir_alimentos_taco('Batata inglesa crua',	64,	2,	0,	15)
        inserir_alimentos_taco('Batata inglesa frita',	267,	5,	13,	36)
        inserir_alimentos_taco('Batata inglesa sauté',	68,	1,	1,	14)
        inserir_alimentos_taco('Berinjela cozida',	19,	1,	0,	4)
        inserir_alimentos_taco('Berinjela crua',	20,	1,	0,	4)
        inserir_alimentos_taco('Beterraba cozida',	32,	1,	0,	7)
        inserir_alimentos_taco('Beterraba crua',	49,	2,	0,	11)
        inserir_alimentos_taco('Biscoito polvilho doce',	438,	1,	12,	81)
        inserir_alimentos_taco('Brócolis cozido',	25,	2,	0,	4)
        inserir_alimentos_taco('Brócolis cru',	25,	4,	0,	4)
        inserir_alimentos_taco('Cará cozido',	78,	2,	0,	19)
        inserir_alimentos_taco('Cará cru',	96,	2,	0,	23)
        inserir_alimentos_taco('Caruru cru',	34,	3,	1,	6)
        inserir_alimentos_taco('Catalonha crua',	24,	2,	0,	5)
        inserir_alimentos_taco('Catalonha refogada',	63,	2,	5,	5)
        inserir_alimentos_taco('Cebola crua',	39,	2,	0,	9)
        inserir_alimentos_taco('Cebolinha crua',	20,	2,	0,	3)
        inserir_alimentos_taco('Cenoura cozida',	30,	1,	0,	7)
        inserir_alimentos_taco('Cenoura crua',	34,	1,	0,	8)
        inserir_alimentos_taco('Chicória crua',	14,	1,	0,	3)
        inserir_alimentos_taco('Chuchu cozido',	19,	0,	0,	5)
        inserir_alimentos_taco('Chuchu cru',	17,	1,	0,	4)
        inserir_alimentos_taco('Coentro folhas desidratadas',	309,	21,	10,	48)
        inserir_alimentos_taco('Couve manteiga crua',	27,	3,	1,	4)
        inserir_alimentos_taco('Couve manteiga refogada', 	90,	2,	7,	9)
        inserir_alimentos_taco('Couve-flor crua',	23,	2,	0,	5)
        inserir_alimentos_taco('Couve-flor cozida',	19,	1,	0,	4)
        inserir_alimentos_taco('Espinafre Nova Zelândia cru',	16,	2,	0,	3)
        inserir_alimentos_taco('Espinafre Nova Zelândia refogado',	67,	3,	5,	4)
        inserir_alimentos_taco('Farinha de mandioca crua',	361,	2,	0,	88)
        inserir_alimentos_taco('Farinha de mandioca torrada',	365,	1,	0,	89)
        inserir_alimentos_taco('Farinha de puba',	360,	2,	0,	87)
        inserir_alimentos_taco('Fécula de mandioca',	331,	1,	0,	81)
        inserir_alimentos_taco('Feijão broto cru',	39,	4,	0,	8)
        inserir_alimentos_taco('Inhame cru',	97,	2,	0,	23)
        inserir_alimentos_taco('Jiló cru',	27,	1,	0,	6)
        inserir_alimentos_taco('Jurubeba crua',	126,	4,	4,	23)
        inserir_alimentos_taco('Mandioca cozida',	125,	1,	0,	30)
        inserir_alimentos_taco('Mandioca crua',	151,	1,	0,	36)
        inserir_alimentos_taco('Mandioca farofa temperada',	406,	2,	9,	80)
        inserir_alimentos_taco('Mandioca frita',	300,	1,	11,	50)
        inserir_alimentos_taco('Manjericão cru',	21,	2,	0,	4)
        inserir_alimentos_taco('Maxixe cru',	14,	1,	0,	3)
        inserir_alimentos_taco('Mostarda folha crua',	18,	2,	0,	3)
        inserir_alimentos_taco('Nhoque batata cozido',	181,	6,	2,	37)
        inserir_alimentos_taco('Nabo cru',	18,	1,	0,	4)
        inserir_alimentos_taco('Palmito juçara em conserva',	23,	2,	0,	4)
        inserir_alimentos_taco('Palmito pupunha em conserva',	29,	2,	0,	6)
        inserir_alimentos_taco('Pão de queijo assado',	363,	5,	25,	34)
        inserir_alimentos_taco('Pão de queijo cru',	295,	4,	14,	39)
        inserir_alimentos_taco('Pepino cru',	10,	1,	0,	2)
        inserir_alimentos_taco('Pimentão amarelo cru',	28,	1,	0,	6)
        inserir_alimentos_taco('Pimentão verde cru',	21,	1,	0,	5)
        inserir_alimentos_taco('Pimentão vermelho cru',	23,	1,	0,	5)
        inserir_alimentos_taco('Polvilho doce',	351,	0,	0,	87)
        inserir_alimentos_taco('Quiabo cru',	30,	2,	0,	6)
        inserir_alimentos_taco('Rabanete cru',	14,	1,	0,	3)
        inserir_alimentos_taco('Repolho branco cru',	17,	1,	0,	4)
        inserir_alimentos_taco('Repolho roxo cru',	31,	2,	0,	7)
        inserir_alimentos_taco('Repolho roxo refogado',	42,	2,	1,	8)
        inserir_alimentos_taco('Rúcula crua',	13,	2,	0,	2)
        inserir_alimentos_taco('Salsa crua',	33,	3,	1,	6)
        inserir_alimentos_taco('Seleta de legumes enlatada',	57,	3,	0,	13)
        inserir_alimentos_taco('Serralha crua',	30,	3,	1,	5)
        inserir_alimentos_taco('Taioba crua',	34,	3,	1,	5)
        inserir_alimentos_taco('Tomate com semente cru',	15,	1,	0,	3)
        inserir_alimentos_taco('Tomate extrato',	61,	2,	0,	15)
        inserir_alimentos_taco('Tomate molho industrializado',	38,	1,	1,	8)
        inserir_alimentos_taco('Tomate purê'	,28,	1,	0,	7)
        inserir_alimentos_taco('Tomate salada',	21,	1,	0,	5)
        inserir_alimentos_taco('Vagem crua',	25,	2,	0,	5)
        inserir_alimentos_taco('Abacate cru',	96,	1,	8,	6)
        inserir_alimentos_taco('Abacaxi cru',	48,	1,	0,	12)
        inserir_alimentos_taco("Carne bovina paleta sem gordura cozida", 194, 30, 7, 0)
        inserir_alimentos_taco('Carne bovina paleta com gordura crua', 159, 21, 7, 0)
        inserir_alimentos_taco('Carne bovina paleta sem gordura crua', 141,21, 6, 0)
        inserir_alimentos_taco('Carne bovina patinho sem gordura cru', 133, 22, 5,0)   
        inserir_alimentos_taco('Carne bovina patinho sem gordura grelhado',	219,36,7,0)
        inserir_alimentos_taco('Carne bovina peito sem gordura cru', 259,18,	20,	0)
        inserir_alimentos_taco('Carne bovina picanha com gordura crua'	,213,	19	,15,	0)
        inserir_alimentos_taco('Carne bovina picanha com gordura grelhada',	289,	26,	20,	0)
        inserir_alimentos_taco('Carne bovina picanha sem gordura crua'	,134,	21,	5,	0)
        inserir_alimentos_taco('Carne bovina picanha sem gordura grelhada'	,238,	32,	11,	0)
        inserir_alimentos_taco('Carne bovina seca cozida',	313	,27,	22,	0)
        inserir_alimentos_taco('Carne bovina seca crua',	313	,20,	25,	0)
        inserir_alimentos_taco('Coxinha de frango frita',	283,	10,	12,	35)
        inserir_alimentos_taco('Croquete de carne cru'	,246,	12,	16,	14)
        inserir_alimentos_taco('Croquete de carne frito',	347,	17,	23,	18)
        inserir_alimentos_taco('Empada de frango pré-cozida assada',	358,	7,	16,	47)
        inserir_alimentos_taco('Empada de frango pré-cozida'	,377	,7,	23,	36)
        inserir_alimentos_taco('Frango asa com pele crua',	213,	18,	15,	0)
        inserir_alimentos_taco('Frango caipira inteiro com pele cozido	',243,	24,	16,	0)
        inserir_alimentos_taco('Frango caipira inteiro sem pele cozido',	196,	30,	8,	0)
        inserir_alimentos_taco('Frango coração cru',	222	,13	,19	,0)
        inserir_alimentos_taco('Frango coração grelhado'	,207,	22,	12,	1)
        inserir_alimentos_taco('Coxa de Frango com pele assada',	215,	28,	10,	0)
        inserir_alimentos_taco('Coxa de Frango  com pele crua',	161,	17,	10,	0)
        inserir_alimentos_taco('Coxa de Frango  sem pele cozida',	167,	27,	6,	0)
        inserir_alimentos_taco('Coxa de Frango  sem pele crua',	120	,18,	5,	0)
        inserir_alimentos_taco('Frango fígado cru'	,106,	18,	3,	0)
        inserir_alimentos_taco('Frango filé à milanesa',	221,	28,	8,	8)
        inserir_alimentos_taco('Frango inteiro com pele cru',	226,	16,	17,	0)
        inserir_alimentos_taco('Frango inteiro sem pele assado',	187,	28,	8,	0)
        inserir_alimentos_taco('Frango inteiro sem pele cozido',	170	,25,	7,	0)
        inserir_alimentos_taco('Frango inteiro sem pele cru',	129,	21,	5,	0)
        inserir_alimentos_taco('Peito de Frango com pele assado',	212	,33,	8,	0)
        inserir_alimentos_taco('Peito de Frango com pele cru',	149,	21,	7,	0)
        inserir_alimentos_taco('Peito de Frango sem pele cozido'	,163,	31,	3,	0)
        inserir_alimentos_taco('Peito de Frango sem pele cru'	,119,	22,	3,	0)
        inserir_alimentos_taco('Peito de Frango sem pele grelhado',	159,	32,	2,	0)
        inserir_alimentos_taco('Sobrecoxa de Frango com pele assada'	,260	,29	,15,	0)
        inserir_alimentos_taco('Sobrecoxa de Frango com pele crua',	255,	15,	21,	0)
        inserir_alimentos_taco('Sobrecoxa de Frango sem pele assada',	233	,29	,12,	0)
        inserir_alimentos_taco('Sobrecoxa de Frango sem pele crua',	162,	18,	10,	0)
        inserir_alimentos_taco('Hambúrguer bovino cru'	,215	,13	,16	,4)
        inserir_alimentos_taco('Hambúrguer bovino frito',258,	20,	17,	6)
        inserir_alimentos_taco('Hambúrguer bovino grelhado',	210,	13,	12	,11)
        inserir_alimentos_taco('Lingüiça de frango crua'	,218	,14	,17,	0)
        inserir_alimentos_taco('Lingüiça de frango frita'	,245,	18,	19,	0)
        inserir_alimentos_taco('Lingüiça de frango grelhada'	,244,	18,	18,	0)
        inserir_alimentos_taco('Lingüiça de porco crua'	,227,	16,	18,	0)
        inserir_alimentos_taco('Lingüiça de porco frita'	,280	,20,	21,	0)
        inserir_alimentos_taco('Lingüiça de porco grelhada',	296,	23,	22,	0)
        inserir_alimentos_taco('Mortadela',	269,	12	,22	,6)
        inserir_alimentos_taco('Peru congelado assado'	,163,	26	,6,	0)
        inserir_alimentos_taco('Peru congelado cru',	94,	18	,2,	0)
        inserir_alimentos_taco('Bisteca de Porco crua',	164,	22,	8,	0)
        inserir_alimentos_taco('Bisteca de Porco frita',	311,	34,	19,	0)
        inserir_alimentos_taco('Bisteca de Porco grelhada',280,29	,17,0)
        inserir_alimentos_taco('Costela de Porco assada',	402,	30,	30,	0)
        inserir_alimentos_taco('Costela de Porco crua',	256,	18,	20,	0)
        inserir_alimentos_taco('Lombo de Porco assado',	210,	36,	6,	0)
        inserir_alimentos_taco('Lombo de Porco cru',	176,	23	,9,	0)
        inserir_alimentos_taco('Porco orelha salgada crua'	,258	,19	,20,	0)
        inserir_alimentos_taco('Porco pernil assado',	262	,32	,14,	0)
        inserir_alimentos_taco('Porco pernil cru'	,186	,20,	11,	0)
        inserir_alimentos_taco('Porco rabo salgado cru',377,	16,	34,	0)
        inserir_alimentos_taco('Presunto com capa de gordura',	128,	14,	7,	1)
        inserir_alimentos_taco('Presunto sem capa de gordura'	,94	,14,	3,	2)
        inserir_alimentos_taco('Quibe assado',	136	,15,	3,	13)
        inserir_alimentos_taco('Quibe cru',	109,	12,	2,	11)
        inserir_alimentos_taco('Quibe frito', 254, 15,	16,	12)
        inserir_alimentos_taco('Salame', 398	,26, 31,	3)
        inserir_alimentos_taco('Toucinho cru', 593, 11,	60,	0)
        inserir_alimentos_taco('Toucinho frito', 697 , 27, 64, 0)
        inserir_alimentos_taco('Bebida láctea pêssego',	55,	2,	2,	8)
        inserir_alimentos_taco('Creme de Leite', 221,	2,	22,	5)
        inserir_alimentos_taco('Iogurte natural', 51,	4,	3,	2)
        inserir_alimentos_taco('Iogurte natural desnatado', 41,	4,	0,6)
        inserir_alimentos_taco('Iogurte sabor abacaxi', 111,	7,	5,	9)
        inserir_alimentos_taco('Iogurte sabor morango', 70,	3,	2,	10)
        inserir_alimentos_taco('Iogurte sabor pêssego',	68,	3,	2,	9)
        inserir_alimentos_taco('Leite condensado', 313,	8,	7,	57)
        inserir_alimentos_taco('Leite de cabra', 66,	3,	4	,5)
        inserir_alimentos_taco('Leite de vaca achocolatao',	83,	2,	2,	14)
        inserir_alimentos_taco('Leite de vaca desnatado pó',	362,	35,	1,	53)
        inserir_alimentos_taco('Leite de vaca desnatado UHT',	61,	6,	0	,9)
        inserir_alimentos_taco('Leite de vaca integral',	60,	3,	3,	5)
        inserir_alimentos_taco('Leite de vaca integral pó'	,497,	25,	27,	39)
        inserir_alimentos_taco('Leite fermentado',	70,	2,	0,	16)
        inserir_alimentos_taco('Queijo minas frescal',	264,	17,	20	,3)
        inserir_alimentos_taco('Queijo minas meia cura',	321,	21,	25,	4)
        inserir_alimentos_taco('Queijo mozarela',	330,	23,	25,	3)
        inserir_alimentos_taco('Queijo parmesão'	,453,	36,	34,	2)
        inserir_alimentos_taco('Queijo pasteurizado',	303,	9,	27,	6)
        inserir_alimentos_taco('Queijo petit suisse morango',	121, 6, 3, 18)
        inserir_alimentos_taco('Queijo prato', 360, 23,	29,	2)
        inserir_alimentos_taco('Queijo requeijão cremoso',	257, 10, 23, 2)
        inserir_alimentos_taco('Queijo ricota', 140, 13, 8, 4)
        inserir_alimentos_taco('Bebida isotônica sabores variados',	26,	0,	0, 6)
        inserir_alimentos_taco('Café infusão 10%',	9,	1,	0,	1)	
        inserir_alimentos_taco('Cerveja pilsen', 41,	1,	0,	3)
        inserir_alimentos_taco('Chá erva-doce infusão 5%',	1,	0,	0,	0)
        inserir_alimentos_taco('Chá mate infusão 5%', 3,	0, 0, 1)
        inserir_alimentos_taco('Chá preto infusão 5%',	2,	0,	0, 1)
        inserir_alimentos_taco('água de coco',	22,	0,	0,	5)
        inserir_alimentos_taco('Refrigerante tipo água tônica',	31,	0,	0,	8)
        inserir_alimentos_taco('Refrigerante tipo cola', 34,	0,	0,	9)
        inserir_alimentos_taco('Refrigerante tipo guaraná', 39	,0,	0,	10)
        inserir_alimentos_taco('Refrigerante tipo laranja',	46,	0 , 0 , 12)
        inserir_alimentos_taco('Refrigerante tipo limão', 40,	0,	0 ,	10)
        inserir_alimentos_taco('Omelete de queijo', 268, 16,	22 , 0)
        inserir_alimentos_taco('Ovo de codorna inteiro cru'	, 177, 14,	13,	1)
        inserir_alimentos_taco('Ovo de galinha clara cozida/10minutos',	59,	13,	0,	0)
        inserir_alimentos_taco('Ovo de galinha gema cozida/10minutos',	353 , 16, 31, 2)
        inserir_alimentos_taco('Ovo de galinha inteiro cozido/10minutos',	146	,13,	9,	1)
        inserir_alimentos_taco('Ovo de galinha inteiro cru', 143,	13,	9,	2)
        inserir_alimentos_taco('Ovo de galinha inteiro frito', 240,	16,	19,	1)
        inserir_alimentos_taco('Achocolatado pó', 401,	4,	2,	91)
        inserir_alimentos_taco('Açúcar cristal', 387,	0,	0,	100)
        inserir_alimentos_taco('Açúcar mascavo', 369,	1,	0,	94)
        inserir_alimentos_taco('Açúcar refinado', 387,	0,	0,	100)
        inserir_alimentos_taco('Chocolate ao leite', 540,	7,	30,	60)
        inserir_alimentos_taco('Chocolate ao leite com castanha do Pará', 559, 7, 34, 55)
        inserir_alimentos_taco('Chocolate ao leite dietético', 557, 7,	34,	56)
        inserir_alimentos_taco('Chocolate meio amargo', 475,	5,	30,	62)
        inserir_alimentos_taco('Cocada branca',	449, 1,	14,	81)
        inserir_alimentos_taco('Doce de abóbora cremoso', 199,	1,	0,	55)
        inserir_alimentos_taco('Doce de leite cremoso', 306	,5,	6,	59)
        inserir_alimentos_taco('Geléia de mocotó natural', 106,	2,	0,	24)
        inserir_alimentos_taco('Glicose de milho', 292,	0,	0,	79)
        inserir_alimentos_taco('Maria mole', 301, 4, 0, 74)
        inserir_alimentos_taco('Maria mole coco queimado', 307,	4,	0,	75)
        inserir_alimentos_taco('Marmelada', 257,	0,	0,	71)
        inserir_alimentos_taco('Mel de abelha',	309,	0,	0,	84)
        inserir_alimentos_taco('Melado', 297,	0,	0,	77)
        inserir_alimentos_taco('Quindim', 411,	5,	24,	46)
        inserir_alimentos_taco('Rapadura', 352,	1,	0,	91)
        inserir_alimentos_taco('Café em pó torrado', 419	,15	,12,	66)
        inserir_alimentos_taco('Capuccino em pó', 417	, 11, 9,74)
        inserir_alimentos_taco('Fermento em pó químico', 90, 0,	0, 44)
        inserir_alimentos_taco('Fermento biológico levedura tablete', 90, 17, 2, 8)
        inserir_alimentos_taco('Gelatina sabores variados pó', 380,	9,	0,	89)
        inserir_alimentos_taco('Shoyu',	61,	3,	0,	12)
        inserir_alimentos_taco('Azeitona preta em conserva', 194,	1,	20,	6)
        inserir_alimentos_taco('Azeitona verde em conserva', 137,	1	,14,	4)
        inserir_alimentos_taco('Chantilly spray com gordura vegetal', 315, 1, 27, 17)
        inserir_alimentos_taco('Leite de coco', 166, 1, 18,	2)
        inserir_alimentos_taco('Maionese tradicional com ovos', 302, 1,	30,	8)
        inserir_alimentos_taco('Acarajé', 289,	8,	20,	19)
        inserir_alimentos_taco('Arroz carreteiro', 154,	11,	7,	12)
        inserir_alimentos_taco('Baião de dois arroz e feijão-de-corda', 136, 6, 3, 20)
        inserir_alimentos_taco('Barreado'	,165,	18,	10,	0)
        inserir_alimentos_taco('Bife à cavalo com contra filé'	,291	,24	,21,	0)
        inserir_alimentos_taco('Bolinho de arroz'	,274,	8,	8,	42)
        inserir_alimentos_taco('Camarão à baiana'	,101,	8,	6,	3)
        inserir_alimentos_taco('Charuto de repolho'	,78,	7,	1,	10)
        inserir_alimentos_taco('Cuscuz de milho cozido com sal'	,113,	2,	1,	25)
        inserir_alimentos_taco('Cuscuz paulista'	,142,	3,	5	,23)
        inserir_alimentos_taco('Cuxá molho'	,80	,6	,4,	6)
        inserir_alimentos_taco('Dobradinha'	,125,	20,	4,	0)
        inserir_alimentos_taco('Estrogonofe de carne'	,173,	15,	11,	3)
        inserir_alimentos_taco('Estrogonofe de frango',157,	18,	8,	3)
        inserir_alimentos_taco('Feijão tropeiro mineiro'	,152,	10,	7,	20)
        inserir_alimentos_taco('Feijoada'	,117,	9,	6	,12)
        inserir_alimentos_taco('Frango com açafrão'	,113,	10,	6,	4)
        inserir_alimentos_taco('Macarrão molho bolognesa'	,120,	5,	1,	23)
        inserir_alimentos_taco('Maniçoba'	,134,	10,	9,	3)
        inserir_alimentos_taco('Quibebe'	,86	,9,	3,	7)
        inserir_alimentos_taco('Salada de legumes com maionese'	,96,	1,	7,	9)
        inserir_alimentos_taco('Salada de legumes cozida no vapor'	,35	,2,	0,	7)
        inserir_alimentos_taco('Salpicão de frango'	,148,	14,	8,	5)
        inserir_alimentos_taco('Sarapatel'	,123,	18,	4,	1)
        inserir_alimentos_taco('Tabule'	,57	,2,	1,	11)
        inserir_alimentos_taco('Tacacá	',47,	7,	0,	3)
        inserir_alimentos_taco('Tapioca com manteiga'	, 348,0	,11	,64)
        inserir_alimentos_taco('Tucupi com pimenta-de-cheiro', 27,	2,	0,	5)
        inserir_alimentos_taco('Vaca atolada',145,	5,	9	,10)
        inserir_alimentos_taco('Vatapá',255,	6,	23,	10)
        inserir_alimentos_taco('Virado à paulista'	,307,	10,	26,	14)
        inserir_alimentos_taco('Yakisoba'	,113,	8,	3	,18)
        inserir_alimentos_taco('Amendoim grão cru',544,	27,	44,	20)
        inserir_alimentos_taco('Amendoim torrado salgado'	,606,	22,	54,	19)
        inserir_alimentos_taco('Ervilha em vagem', 88, 7,	0	,14)
        inserir_alimentos_taco('Ervilha enlatada drenada',	74,	5,	0,	13)
        inserir_alimentos_taco('Feijão carioca cozido',	76,	5,	1,	14)
        inserir_alimentos_taco('Feijão carioca cru',	329,	20	,1,	61)
        inserir_alimentos_taco('Feijão fradinho cozido',78	,5	,1	,13)
        inserir_alimentos_taco('Feijão fradinho cru', 339,	20,	2,	61)
        inserir_alimentos_taco('Feijão jalo cozido', 93,	6,	1,	16)
        inserir_alimentos_taco('Feijão jalo cru	', 328,	20,	1,	61)
        inserir_alimentos_taco('Feijão preto cozido', 77	,4,	1,	14)
        inserir_alimentos_taco('Feijão preto cru', 324	,21,	1	,59)
        inserir_alimentos_taco('Feijão rajado cozido', 85,	6,	0,	15)
        inserir_alimentos_taco('Feijão rajado cru', 326,	17,	1,	63)
        inserir_alimentos_taco('Feijão rosinha cozido',	68,	5,	0,	12)
        inserir_alimentos_taco('Feijão rosinha cru', 337,	21,	1,	62)
        inserir_alimentos_taco('Feijão roxo cozido', 77,	6,	1,	13)
        inserir_alimentos_taco('Feijão roxo cru', 331	,22	,1,	60)
        inserir_alimentos_taco('Grão-de-bico cru', 355,21,	5,	58)
        inserir_alimentos_taco('Guandu cru', 344, 19 , 2 , 64)
        inserir_alimentos_taco('Lentilha cozida', 93, 6, 1,	16)
        inserir_alimentos_taco('Lentilha crua',	339, 23, 1,	62)
        inserir_alimentos_taco('Paçoca de amendoim', 487, 16, 26, 52)
        inserir_alimentos_taco('Pé-de-moleque de amendoim'	, 503, 13, 28, 55)
        inserir_alimentos_taco('Soja farinha', 404, 36,	15,	38)
        inserir_alimentos_taco('Soja extrato solúvel natural fluido', 39, 2, 2, 4)
        inserir_alimentos_taco('Soja extrato solúvel em pó',	459,	36,	26,	28)
        inserir_alimentos_taco('Soja queijo (tofu)',	64,	7,	4,	2)
        inserir_alimentos_taco('Tremoço cru',	381,	34,	10,	44)
        inserir_alimentos_taco('Tremoço em conserva	',121,	11,	4,	12)
        inserir_alimentos_taco('Amêndoa torrada salgada',	581,	19,	47,	30)
        inserir_alimentos_taco('Castanha-de-caju torrada salgada'	,570,	19,	46,	29)
        inserir_alimentos_taco('Castanha-do-Brasil crua	',643,	15,	63,	15)
        inserir_alimentos_taco('Coco cru', 406,	4,	42,	10)
        inserir_alimentos_taco('Farinha de mesocarpo de babaçu crua', 329,	1,	0,	79)
        inserir_alimentos_taco('Gergelim semente', 584,	21,	50,	22)
        inserir_alimentos_taco('Linhaça semente', 495,	14,	32,	43)
        inserir_alimentos_taco('Pinhão cozido',	174,3,	1,	44)
        inserir_alimentos_taco('Pupunha cozida'	, 219,	3,	13,	30)
        inserir_alimentos_taco('Abacaxi polpa congelada',	31,	0,	0,	8)
        inserir_alimentos_taco('Abiu cru',	62,	1,	1	,15)
        inserir_alimentos_taco('Açaí polpa com xarope de guaraná e glucose',	110	,1	,4	,21)
        inserir_alimentos_taco('Açaí polpa congelada',	58,	1,	4	,6)
        inserir_alimentos_taco('Acerola crua',	33	,1	,0,	8)
        inserir_alimentos_taco('Acerola polpa congelada',	22,	1	,0,	6)
        inserir_alimentos_taco('Ameixa calda enlatada', 	183	,0	,0	,47)
        inserir_alimentos_taco('Ameixa crua',	53	,1	,0,	14)
        inserir_alimentos_taco('Ameixa em calda enlatada drenada', 	177,	1,	0,	48)
        inserir_alimentos_taco('Atemóia crua',	97,	1,	0,	25)
        inserir_alimentos_taco('Banana da terra crua',	128,	1,	0,	34)
        inserir_alimentos_taco('Banana doce em barra',	280,	2,	0,	76)
        inserir_alimentos_taco('Banana figo crua',	105,	1,	0,	28)
        inserir_alimentos_taco('Banana maçã crua',	87,	2,	0,	22)
        inserir_alimentos_taco('Banana nanica crua',	92,	1,	0,	24)
        inserir_alimentos_taco('Banana ouro crua',	112,	1,	0,	29)
        inserir_alimentos_taco('Banana pacova crua',	78,	1,	0,	20)
        inserir_alimentos_taco('Banana prata crua',	98,	1,	0,	26)
        inserir_alimentos_taco('Cacau cru',	74,	1,	0,	19)
        inserir_alimentos_taco('Cajá-Manga cru',	46,	1,	0,	11)
        inserir_alimentos_taco('Cajá polpa congelada',	26,	1,	0,	6)
        inserir_alimentos_taco('Caju cru',	43,	1,	0,	10)
        inserir_alimentos_taco('Caju polpa congelada',	37,	0,	0,	9)
        inserir_alimentos_taco('Caju suco concentrado  envasado',	45,	0,	0,	11)
        inserir_alimentos_taco('Caqui chocolate cru',	71,	0,	0,	19)
        inserir_alimentos_taco('Carambola crua',	46,1,	0,	11)
        inserir_alimentos_taco('Ciriguela crua',	76,	1,	0,	19)
        inserir_alimentos_taco('Cupuaçu cru',	49,	1,	1,	10)
        inserir_alimentos_taco('Cupuaçu polpa congelada',	49,	1,	1,	11)
        inserir_alimentos_taco('Figo cru',	41,	1,	0,	10)
        inserir_alimentos_taco('Figo enlatado em calda',	184,	1,	0,	50)
        inserir_alimentos_taco('Fruta-pão crua',	67,	1,	0,	17)
        inserir_alimentos_taco('Goiaba branca com casca crua',	52,	1,	0,	12)
        inserir_alimentos_taco('Goiaba doce em pasta',	269,	1	,0,	74)
        inserir_alimentos_taco('Goiaba doce cascão',	286,	0,	0,	79)
        inserir_alimentos_taco('Goiaba vermelha com casca crua',	54,	1,	0,	13)
        inserir_alimentos_taco('Graviola crua',	62,	1,	0,	16)
        inserir_alimentos_taco('Graviola polpa congelada',	38,	1,	0,	10)
        inserir_alimentos_taco('Jabuticaba crua',	58,	1,0,	15)
        inserir_alimentos_taco('Jaca crua',	88,	1,	0	,22)
        inserir_alimentos_taco('Jambo cru',	27,	1,	0,	6)
        inserir_alimentos_taco('Kiwi cru' ,51,	1,	1,	11)
        inserir_alimentos_taco('Laranj baía crua'	,45,	1,	0,	11)
        inserir_alimentos_taco('Laranja baía suco'	,37,	1,	0,	9)
        inserir_alimentos_taco('Laranja da terra crua',	51,	1,	0,	13)
        inserir_alimentos_taco('Laranja da terra suco',	41	,1,0	,10)
        inserir_alimentos_taco('Laranja lima crua',	46,	1,	0,	12)
        inserir_alimentos_taco('Laranja lima suco'	,39	,1,	0	,9)
        inserir_alimentos_taco('Laranja pêra crua',37	,1	,0	,9)
        inserir_alimentos_taco('Laranja pêra suco'	,33	,1,	0,8)
        inserir_alimentos_taco('Laranja valência crua'	,46,	1	,0,	12)
        inserir_alimentos_taco('Laranja valência suco',	36,	0,	0,9)
        inserir_alimentos_taco('Limão cravo suco'	,14,	0	,0,5)
        inserir_alimentos_taco('Limão galego suco'	,22	,1,	0,	7)
        inserir_alimentos_taco('Limão tahiti cru'	,32	,1,	0,	11)
        inserir_alimentos_taco('Maçã Argentina com casca crua',	63,	0,	0,	17)
        inserir_alimentos_taco('Maçã Fuji com casca crua',	56,	0,	0,	15)
        inserir_alimentos_taco('Macaúba crua'	,404,	2,	41,	14)
        inserir_alimentos_taco('Mamão doce em calda, drenado'	,196,	0,	0,	54)
        inserir_alimentos_taco('Mamão Formosa cru',	45,	1,	0,	12)
        inserir_alimentos_taco('Mamão Papaia cru'	,40	,0,	0,	10)
        inserir_alimentos_taco('Mamão verde doce em calda drenado'	,209,0	,0	,58)
        inserir_alimentos_taco('Manga Haden crua'	,64,0,	0,	17)
        inserir_alimentos_taco('Manga Palmer crua',	72,	0,	0,	19)
        inserir_alimentos_taco('Manga polpa congelada'	,48	,0,	0,	13)
        inserir_alimentos_taco('Manga Tommy Atkins crua'	,51	,1,	0,	13)
        inserir_alimentos_taco('Maracujá cru'	,68	,2,	2,12)
        inserir_alimentos_taco('Maracujá polpa congelada'	,39,	1	,0,	10)
        inserir_alimentos_taco('Maracujá suco concentrado envasado',	42,	1	,0,	10)
        inserir_alimentos_taco('Melancia crua',33	,1	,0	,8)
        inserir_alimentos_taco('Melão cru',	29,	1,	0	,8)
        inserir_alimentos_taco('Mexerica Murcote crua'	,58,	1	,0,	15)
        inserir_alimentos_taco('Mexerica Rio crua'	,37	,1,	0,	9)
        inserir_alimentos_taco('Morango cru'	,30	,1,	0,	7)
        inserir_alimentos_taco('Nêspera crua'	,43	,0,	0,	12)
        inserir_alimentos_taco('Pequi cru'	,205,	2,	18,	13)
        inserir_alimentos_taco('Pêra Park crua',	61,	0,	0	,16)
        inserir_alimentos_taco('Pêra William crua'	,53	,1,	0,	14)
        inserir_alimentos_taco('Pêssego Aurora cru'	,36,	1,	0,	9)
        inserir_alimentos_taco('Pêssego enlatado em calda'	,63	,1,	0,	17)
        inserir_alimentos_taco('Pinha crua'	,88	,1	,0,	22)
        inserir_alimentos_taco('Pitanga crua'	,41,	1,	0	,10)
        inserir_alimentos_taco('Pitanga polpa congelada'	,19	,0,	0,	5)
        inserir_alimentos_taco('Romã crua'	,56	,0	,0,	15)
        inserir_alimentos_taco('Tamarindo cru'	,276,	3	,0,	73)
        inserir_alimentos_taco('Tangerina Poncã crua'	,38,	1	,0,	10)
        inserir_alimentos_taco('Tangerina Poncã suco'	,36	,1,	0,	9)
        inserir_alimentos_taco('Tucumã cru'	,262,	2	,19	,26)
        inserir_alimentos_taco('Umbu cru'	,37	,1,	0	,9)
        inserir_alimentos_taco('Umbu polpa congelada'	,34,	1,	0,	9)
        inserir_alimentos_taco('Uva Itália crua'	,53	,1,	0	,14)
        inserir_alimentos_taco('Uva Rubi crua',	49	,1	,0,	13)
        inserir_alimentos_taco('Uva suco concentrado envasado',	58	,0,	0,	15)
        inserir_alimentos_taco('Azeite de dendê',884,0	,100,	0)
        inserir_alimentos_taco('Azeite de oliva extra virgem'	,884,	0,	100,	0)
        inserir_alimentos_taco('Manteiga com sal'	,726,	0	,82,	0)
        inserir_alimentos_taco('Manteiga sem sal',	758,0	,86	,0)
        inserir_alimentos_taco('Margarina com óleo hidrogenado com sal (65% de lipídeos)'	,596,	0,	67,	0)
        inserir_alimentos_taco('Margarina com óleo hidrogenado sem sal (80% de lipídeos)'	,723,	0,	82,	0)
        inserir_alimentos_taco('Margarina com óleo interesterificado com sal (65%de lipídeos)'	,594,	0,67,	0)
        inserir_alimentos_taco('Margarina com óleo interesterificado sem sal (65% de lipídeos)',	593,	0,	67,	0)
        inserir_alimentos_taco('Óleo de babaçu',	884,	0,	100,0)
        inserir_alimentos_taco('Óleo de canola'	,884,	0	,100,	0)
        inserir_alimentos_taco('Óleo de girassol',	884,	0,	100,	0)
        inserir_alimentos_taco('Óleo de milho',884,	0,	100	,0)
        inserir_alimentos_taco('Óleo de pequi'	,884,	0	,100,	0)
        inserir_alimentos_taco('Óleo de soja'	,884,	0	,100,	0)		
        inserir_alimentos_taco('Abadejo filé congelado assado',	112	,24,	1,	0)
        inserir_alimentos_taco('Abadejo filé congelado cozido'	,91,	19	,1	,0)
        inserir_alimentos_taco('Abadejo filé congelado cru',	59,	13	,0	,0)
        inserir_alimentos_taco('Abadejo filé congelado grelhado'	,130,	28,	1	,0)
        inserir_alimentos_taco('Atum conserva em óleo'	,166,	26,	6	,0)
        inserir_alimentos_taco('Atum fresco cru'	,118,	26,	1	,0)
        inserir_alimentos_taco('Bacalhau salgado cru',	136,	29,	1,	0)
        inserir_alimentos_taco('Bacalhau salgado refogado'	,140,	24,	4	,1)
        inserir_alimentos_taco('Cação posta com farinha de trigo frita'	,208,	25,	10	,3)
        inserir_alimentos_taco('Cação posta cozida'	,116,	26,	1	,0)
        inserir_alimentos_taco('Cação posta crua',	83	,18,	1,	0)
        inserir_alimentos_taco('Camarão Rio Grande grande cozido'	,90	,19,	1,	0)
        inserir_alimentos_taco('Camarão Rio Grande grande cru'	,47	,10,	1,	0)
        inserir_alimentos_taco('Camarão Sete Barbas sem cabeça com casca frito'	,231,	18,	16,3)
        inserir_alimentos_taco('Caranguejo cozido',	83	,18,	0,	0)
        inserir_alimentos_taco('Corimba cru'	,128,	17,	6,	0)
        inserir_alimentos_taco('Corimbatá assado'	,261,	20,	20,	0)
        inserir_alimentos_taco('Corimbatá cozido'	,239,	20,	17,	0)
        inserir_alimentos_taco('Corvina de água doce, crua'	,101,	19,	2	,0)
        inserir_alimentos_taco('Corvina do mar crua'	,94,	19	,2,	0)
        inserir_alimentos_taco('Corvina grande assada'	,147,	27,	4	,0)
        inserir_alimentos_taco('Corvina grande cozida',	100	,23,	3,	0)
        inserir_alimentos_taco('Dourada de água doce fresca'	,131,	19,	6,	0)
        inserir_alimentos_taco('Lambari congelado cru'	,131,	17,	7,	0)
        inserir_alimentos_taco('Lambari congelado frito'	,327,	28,	23,	0)
        inserir_alimentos_taco('Lambari fresco cru'	,152,	16,	9,	0)
        inserir_alimentos_taco('Manjuba com farinha de trigo frita',	344,	23,	23,	10)
        inserir_alimentos_taco('Manjuba frita',	349,	30,	24	,0)
        inserir_alimentos_taco('Merluza filé assado'	,122,	27,	1,	0)
        inserir_alimentos_taco('Merluza filé cru'	,89	,17,	2,	0)
        inserir_alimentos_taco('Merluza filé frito'	,192,	27,	8,	0)
        inserir_alimentos_taco('Pescada branca crua',	111,	16,	5,	0)
        inserir_alimentos_taco('Pescada branca frita'	,223,	27,	12,	0)
        inserir_alimentos_taco('Pescada filé com farinha de trigo frito',	283,	21,	19,	5)
        inserir_alimentos_taco('Pescada filé cru'	,107	,17,	4,	0)
        inserir_alimentos_taco('Pescada filé frito'	,154,	29,	4	,0)
        inserir_alimentos_taco('Pescadinha crua'	,76	,15	,1	,0)
        inserir_alimentos_taco('Pintado assado'	,192	,36	,4,	0)
        inserir_alimentos_taco('Pintado cru'	,91	,19	,1,	0)
        inserir_alimentos_taco('Pintado grelhado'	,152,	31,	2,	0)
        inserir_alimentos_taco('Porquinho cru'	,93,	20,	1,	0)
        inserir_alimentos_taco('Salmão filé com pele fresco  grelhado'	,229	,24,	14,	0)
        inserir_alimentos_taco('Salmão sem pele fresco cru'	,170,	19,	10,	0)
        inserir_alimentos_taco('Salmão sem pele fresco grelhado'	,243	,26,	15,	0)
        inserir_alimentos_taco('Sardinha assada'	,164	,32	,3	,0)
        inserir_alimentos_taco('Sardinha conserva em óleo',	285,	16,	24,	0)
        inserir_alimentos_taco('Sardinha frita',	257,	33,	13,	0)
        inserir_alimentos_taco('Sardinha inteira, crua',	114,	21,	3,	0)
        inserir_alimentos_taco('Tucunaré filé congelado, cru',	88,	18,	1,	0)
        inserir_alimentos_taco('Apresuntado'	,129,	13,	7,	3)
        inserir_alimentos_taco('Caldo de carne tablete',	241,	8,	17,	15)
        inserir_alimentos_taco('Caldo de galinha tablete',	251,	6,	20,	11)
        inserir_alimentos_taco('Carne bovina Acém moído cozido',	212,	27,	11,	0)
        inserir_alimentos_taco('Carne bovina Acém moído cru',	137,	19,	6,	0)
        inserir_alimentos_taco('Carne bovina Acém sem gordura, cozido',	215,	27,	11,	0)
        inserir_alimentos_taco('Carne bovina Acém sem gordura, cru',	144,	21,	6,	0)
        inserir_alimentos_taco('Carne bovina Almôndegas cruas',	189,	12,	11,	10)
        inserir_alimentos_taco('Carne bovina Almôndegas fritas',	272,	18,	16,	14)
        inserir_alimentos_taco('Carne bovina Bucho cozido',	133,	22,	5,	0)
        inserir_alimentos_taco('Carne bovina Bucho cru',	137,	21,	6,	0)
        inserir_alimentos_taco('Carne bovina Capa de contra-filé com gordura crua',	217,	19,	15,	0)
        inserir_alimentos_taco('Carne bovina Capa de contra-filé com gordura grelhada',	312,	31,	20,	0)
        inserir_alimentos_taco('Carne bovina Capa de contra-filé sem gordura crua',	131,	22,	4,	0)
        inserir_alimentos_taco('Carne bovina Capa de contra-filé sem gordura grelhada',	239,	35,	10,	0)
        inserir_alimentos_taco('Carne bovina Charque cozido',	263,	36,	12,	0)
        inserir_alimentos_taco('Carne bovina Charque cru',	249,	23,	17,	0)
        inserir_alimentos_taco('Carne bovina Contra-filé à milanesa',	352,	21,	24,	12)
        inserir_alimentos_taco('Carne bovina Contra-filé de costela cru',	202,	20,	13,	0)
        inserir_alimentos_taco('Carne bovina Contra-filé de costela grelhado',	275,	30,	16,	0)
        inserir_alimentos_taco('Carne bovina Contra-filé com gordura cru',	206,	21,	13,	0)
        inserir_alimentos_taco('Carne bovina Contra-filé com gordura grelhado',	278,	32,	15,	0)
        inserir_alimentos_taco('Carne bovina Contra-filé sem gordura cru',	157,	24,	6,	0)
        inserir_alimentos_taco('Carne bovina Contra-filé sem gordura grelhado',	194,	36,	4,	0)
        inserir_alimentos_taco('Carne bovina Costela assada',	373,	29,	28,	0)
        inserir_alimentos_taco('Carne bovina Costela crua',	358,	17,	32,	0)
        inserir_alimentos_taco('Carne bovina Coxão duro sem gordura cozido',	217,	32,	9,	0)
        inserir_alimentos_taco('Carne bovina Coxão duro sem gordura cru',	148,	22,	6,	0)
        inserir_alimentos_taco('Carne bovina Coxão mole sem gordura cozido',	219,	32,	9,	0)
        inserir_alimentos_taco('Carne bovina Coxão mole sem gordura cru',	169,	21,	9,	0)
        inserir_alimentos_taco('Carne bovina Cupim assado',	330,	29,	23,	0)
        inserir_alimentos_taco('Carne bovina Cupim cru',	221,	20,	15,	0)
        inserir_alimentos_taco('Carne bovina Fígado cru',	141,	21,	5,	1)
        inserir_alimentos_taco('Carne bovina Fígado grelhado',	225,	30,	9,	4)
        inserir_alimentos_taco('Carne bovina Filé mingnon sem gordura cru',	143,	22,	6,	0)
        inserir_alimentos_taco('Carne bovina Filé mingnon sem gordura grelhado',	220,	33,	9,	0)
        inserir_alimentos_taco('Carne bovina Flanco sem gordura cozido',	196,	29,	8,	0)
        inserir_alimentos_taco('Carne bovina Flanco sem gordura cru',	141,	20,	6,	0)
        inserir_alimentos_taco('Carne bovina Fraldinha com gordura cozida',	338,	24,	26,	0)
        inserir_alimentos_taco('Carne bovina Fraldinha com gordura crua',	221,	18,	16,	0)
        inserir_alimentos_taco('Carne bovina Lagarto cozido',	222,	33,	9,	0)
        inserir_alimentos_taco('Carne bovina Lagarto cru',	135,	21,	5,	0)
        inserir_alimentos_taco('Carne bovina Língua cozida',	315,	21,	25,	0)
        inserir_alimentos_taco('Carne bovina Língua crua',	215,	17,	16,	0)
        inserir_alimentos_taco('Carne bovina Maminha crua',	153,	21,	7,	0)
        inserir_alimentos_taco('Carne bovina Maminha grelhada',	153,	31,	2,	0)
        inserir_alimentos_taco('Carne bovina Miolo de alcatra sem gordura cru',	163,	22,	8,	0)
        inserir_alimentos_taco('Carne bovina Miolo de alcatra sem gordura grelhado',	241,	32,	12,	0)
        inserir_alimentos_taco('Carne bovina Músculo sem gordura cozido',	194,	31,	7,	0)
        inserir_alimentos_taco('Carne bovina Músculo sem gordura cru',	142,	22,	5,	0)
        inserir_alimentos_taco("Pasta de amendoim",533,30,41,10)
        inserir_alimentos_taco('Pipoca light',445, 10,64,12)
        inserir_alimentos_taco("Batata doce rito" ,351, 4 ,12 ,56)
        inserir_alimentos_taco(' Mandioca Assada ',125 ,0, 0, 30)
        inserir_alimentos_taco( 'Mingau de arroz' ,148 ,3, 3, 26)
        inserir_alimentos_taco('Sucrilhos de milho' ,377, 4, 0, 88)
        inserir_alimentos_taco( 'Macarrão Ao alho e óleo' ,186,5,4,30)
        inserir_alimentos_taco('Proteína de soja', 142, 18, 5, 5 )
        inserir_alimentos_taco( 'Couve Cozida', 26, 2, 0, 4)
        inserir_alimentos_taco('Mel' ,304, 0, 0, 82)
        inserir_alimentos_taco( 'Pudim de qualquer sabor', 131, 5, 5, 15)
        inserir_alimentos_taco( 'Brigadeiro', 334,7, 10, 54)
        inserir_alimentos_taco('Quindim',131, 5, 5, 15)
        inserir_alimentos_taco('Kinder ovo' ,535, 7, 29, 59)
        inserir_alimentos_taco('Açúcar', 387,0,0,99)
        inserir_alimentos_taco( 'Requeijão light',231,10,17, 7)
        inserir_alimentos_taco('Cerveja (com ou sem álcool)' ,43, 0,0, 3)
        inserir_alimentos_taco('Suco de laranja',41, 0, 0, 9)
        inserir_alimentos_taco("Whey Protein Max Titanium 100%", 125,21,2,5)
        inserir_alimentos_taco("Whey Protein Growth 80%", 122,23,1,4)
        inserir_alimentos_taco("Whey Protein Integral 100%", 120,21,2,4)
        print(f'TABELA TACO INSERIDA')
    else:
        print(f"ADM JÁ CADASTRADO")
        print(f"TABELA TACO JÁ INSERIDA")
