# Generated by Django 4.0.4 on 2022-05-18 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('protein', models.IntegerField(default=0, null=True)),
                ('fat', models.IntegerField(default=0, null=True)),
                ('carbo', models.IntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name_plural': 'Alimentos',
            },
        ),
    ]
