# Generated by Django 4.0.4 on 2022-05-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='kcal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
